name: uploadgram
description: Uploadgram frontend for Android (and web)

publish_to: 'none'
version: 1.0.0+7

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    dio: ^4.0.0-beta7
    intl: ^0.17.0
    connectivity: ^3.0.2
    connectivity_for_web: ^0.4.0
    url_launcher: ^6.0.3
    path_provider: ^2.0.1
    image: ^3.0.2
    photo_view: ^0.12.0
    hive: ^2.0.4
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    share_plus: ^2.1.4
    synchronized: ^3.0.0
    shimmer_animation: ^2.0.0
    path: ^1.8.0
    file_picker: ^3.0.4
    duration: ^3.0.6
    equatable: ^2.0.3
    flutter_uploader: ^3.0.0-beta.2
    logging: ^1.0.1
    awesome_notifications: ^0.0.6+10
    json_serializable: ^5.0.0
    package_info_plus: ^1.0.5
    crypto: ^3.0.1
    hive_box_generator:
        path: ./hive_box_generator
    provider: ^6.0.1
    tuple: ^2.0.0
    hive_flutter: ^1.1.0

dev_dependencies:
    build_runner: ^2.1.1
    flutter_gen_runner: ^4.0.1
    flutter_lints: ^1.0.0
    flutter_test:
        sdk: flutter
    hive_generator: ^1.1.1

flutter:
    generate: true
    uses-material-design: true
    assets:
        - assets/icon-256.png
