builders:
    hive_box_generator:
        import: 'package:hive_box_generator/builder.dart'
        builder_factories: ['hiveBoxBuilder']
        build_extensions: { '.dart': ['hive_box_generator.g.part'] }
        auto_apply: dependents
        build_to: cache
        applies_builders: ['source_gen|combining_builder']
