import 'package:flutter/material.dart';

const Map<String, IconData> fileIcons = {
  'apk': Icons.android,
  'zip': Icons.archive,
  '7z': Icons.archive,
  'rar': Icons.archive,
  'tar': Icons.archive,
  'gz': Icons.archive,
  'xz': Icons.archive,
  'bz2': Icons.archive,
  'log': Icons.description,
  'txt': Icons.description,
  'docx': Icons.description,
  'doc': Icons.description,
  'odt': Icons.description,
  'md': Icons.font_download,
  'mp4': Icons.movie,
  'avi': Icons.movie,
  'mkv': Icons.movie,
  'webm': Icons.movie,
  'mpeg': Icons.movie,
  'ogv': Icons.movie,
  'ts': Icons.movie,
  'mp3': Icons.audiotrack,
  'aac': Icons.audiotrack,
  'mid': Icons.audiotrack,
  'midi': Icons.audiotrack,
  'oga': Icons.audiotrack,
  'wav': Icons.audiotrack,
  'weba': Icons.audiotrack,
  'opus': Icons.audiotrack,
  'gif': Icons.insert_photo,
  'bmp': Icons.insert_photo,
  'png': Icons.insert_photo,
  'jpg': Icons.insert_photo,
  'jpeg': Icons.insert_photo,
  'tiff': Icons.insert_photo,
  'tif': Icons.insert_photo,
  'ico': Icons.insert_photo,
  'webp': Icons.insert_photo,
  'html': Icons.code,
  'xml': Icons.code,
  'php': Icons.code,
  'py': Icons.code,
  'js': Icons.code,
  'dart': Icons.code,
  'css': Icons.code,
  'svg': Icons.code,
  'json': Icons.code,
  'java': Icons.code,
  'bash': Icons.code,
  'sh': Icons.code,
  'zsh': Icons.code,
  'exe': Icons.settings_applications,
  'jar': Icons.settings_applications,
  'default': Icons.insert_drive_file
};

IconData getFileIconFromName(String filename) {
  return fileIcons[filename.split('.').last.toLowerCase()] ??
      fileIcons['default']!;
}
