name: Build and publish APK

on:
    push:
        tags:
            - v*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Setup Java environment in order to build the Android app.
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: '8'

            # Setup the flutter environment.
            - uses: subosito/flutter-action@v1

            - name: Get packages
              run: flutter pub get
            - name: Run the code builder
              run: |
                  flutter pub run build_runner build --delete-conflicting-outputs
            - name: Generate fat apk
              run: flutter build apk --target-platform=android-arm,android-arm64,android-x64
            - name: Generate per-abi APKs
              run: flutter build apk --target-platform=android-arm,android-arm64,android-x64
            - name: Get SHA256 for all the generated files
              run: |
                  mkdir sha256_sums
                  for file in app-{,arm64-v8a-,armeabi-v7a-,x86_64-}release.apk; do
                    openssl dgst -sha256 "build/app/outputs/flutter-apk/${file}"| sed -E 's/.+ ([0-9a-f]+)/\1/' > "sha256_sums/sha256-${file}.txt"
                  done
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Release binaries
                  path: |
                      build/app/outputs/flutter-apk/app-release.apk
                      build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
                      build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
                      build/app/outputs/flutter-apk/app-x86_64-release.apk
            - name: Upload sha256 artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: SHA256sums
                  path: |
                      sha256_sums/sha256-app-release.apk.txt
                      sha256_sums/sha256-app-arm64-v8a-release.apk.txt
                      sha256_sums/sha256-app-armeabi-v7a-release.apk.txt
                      sha256_sums/sha256-app-x86_64-release.apk.txt
            #- name: Release everything
            #  uses: softprops/action-gh-release@v1
            #  with:
            #      files: |
            #          build/app/outputs/flutter-apk/app-release.apk
            #          build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            #          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            #          build/app/outputs/flutter-apk/app-x86_64-release.apk
            #          sha256_sums/sha256-app-release.apk.txt
            #          sha256_sums/sha256-app-arm64-v8a-release.apk.txt
            #          sha256_sums/sha256-app-armeabi-v7a-release.apk.txt
            #          sha256_sums/sha256-app-x86_64-release.apk.txt
